### ISSUE TITLE
FAILED to handle event: Error: Command failed: git config user.name

### ISSUE THREAD

**Issue by tholst** [carlthome/vscode-git-line-blame#54]
Hi, I just wanted to report that your nice extension (thx!) stopped working for me. I see the following error message.

<img width="1104" alt="image" src="https://github.com/carlthome/vscode-git-line-blame/assets/2027794/0235478e-1458-49a8-8592-d1f79c0918a6">

**Comment by carlthome** [comment]
Oh, thanks for sharing! This came out of https://github.com/carlthome/vscode-git-line-blame/pull/49 (write "You" instead when commit author is the user)

Not sure why `git config user.name` wouldn't work though. Is it that you don't have a username set? Could you try running `git config user.name` in the VS Code integrated terminal to see what you get?

**Comment by tholst** [comment]
I have a user.name set. `git config user.name` from within vscode terminal correctly produces my name.

<img width="172" alt="image" src="https://github.com/carlthome/vscode-git-line-blame/assets/2027794/ca396efb-ce1d-4402-8411-b1ec2f8e0b0a">

**Comment by tholst** [comment]
My first guess would be that `git config user.name` is somehow not executed in the workspace/project folder. Could that be?
